package:
  name: pygenprop
  version: "1.0"

source:
  path: .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy>=1.16.5
    - Cython>=0.29.13
    - pandas>=1.1.5
    - sqlalchemy>=1.3.23
    - scikit-bio>=0.5.5

build:
  script: python -m pip install --no-deps -vv .

test:
  commands:
    - pygenprop -h

about:
  home: https://github.com/Micromeda/pygenprop
  license: APL 2.0
  license_file: LICENSE