# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Python Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6","3.7","3.8","3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose numpy
        python -m pip install .
        git clone https://github.com/Micromeda/genome-properties
    - name: Test with Nose
      run: |
        nosetests -v ./
    - name: Test CLI
      run: |
        ./pygenprop/testing/test_parse_genome_properties_file.py -i ./genome-properties/flatfiles/genomeProperties.txt
        ./pygenprop/testing/test_parse_genome_properties_assignments.py -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.txt -o ./test1.json
        ./pygenprop/testing/test_parse_interproscan.py -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv -o ./test2.json
        pygenprop build -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv pygenprop/testing/test_constants/C_luteolum_DSM_273.tsv -o ./joined_cloroflexi_data.micro -p
        pygenprop build -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv -o ./chloromatii_data.micro -p
        pygenprop build -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_luteolum_DSM_273.tsv -o ./luteolum_data.micro -p
        pygenprop merge -d ./genome-properties/flatfiles/genomeProperties.txt -i ./chloromatii_data.micro ./luteolum_data.micro -o ./merged_cholorflexi_data.micro
        ./pygenprop/testing/test_parse_genome_properties_end_to_end.sh
        ./pygenprop/testing/test_cli.sh