# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Build Python Package Conda

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6","3.7","3.8","3.9"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: pygenprop
        use-mamba: true
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      with:
        path: $CONDA_PREFIX
        key: conda-${{ hashFiles('meta.yaml') }}-${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        mamba install -y -c conda-forge conda-build nose
        mamba env update --file environment.yaml --name pygenprop
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Build and install package
      run: |
        conda build . --no-anaconda-upload -c conda-forge -c bioconda
        BUILD_PATH=$(conda build . --output)
        mamba install -y -c conda-forge -c bioconda $BUILD_PATH
        git clone https://github.com/Micromeda/genome-properties

    - name: Test with Nose
      run: |
        nosetests -v ./

    - name: Test CLI
      run: |
        ./pygenprop/testing/test_parse_genome_properties_file.py -i ./genome-properties/flatfiles/genomeProperties.txt
        ./pygenprop/testing/test_parse_genome_properties_assignments.py -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.txt -o ./test1.json
        ./pygenprop/testing/test_parse_interproscan.py -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv -o ./test2.json
        pygenprop build -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv pygenprop/testing/test_constants/C_luteolum_DSM_273.tsv -o ./joined_cloroflexi_data.micro -p
        pygenprop build -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv -o ./chloromatii_data.micro -p
        pygenprop build -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_luteolum_DSM_273.tsv -o ./luteolum_data.micro -p
        pygenprop merge -d ./genome-properties/flatfiles/genomeProperties.txt -i ./chloromatii_data.micro ./luteolum_data.micro -o ./merged_cholorflexi_data.micro
        ./pygenprop/testing/test_parse_genome_properties_end_to_end.sh
        ./pygenprop/testing/test_cli.sh